dataset:
  dataset_name: haldennord09
  dataset_version: latest
  extension: png
  darwin_root: /darwin/digital-production
dataloader:
  batch_size: 4
  num_workers: 4
model:
  model_name: fasterrcnn
  backbone: resnet50
  train_backbone: False
  weights: COCO_V1
  num_classes: 2
  optimizer: adam
  learning_rate: 0.0001
  epochs: 100
  models_dir: /home/naro/projects/Rumex/artifacts/models
